#y^2 = x^3 + ax + b
#ECC_Associative (elliptic curve associative test) 
    #check (check p is on the ecc or not) 
    #findcoord (find the coordinates of giving x on the curve) 
    #recordNcoord (record all N coordinates) 
    #test (test the ecc match associative law or not)
    #add (modadd) 
    #mul (montgomary ladder) 
#test
from Crypto.Util.number import isPrime
from textwrap import dedent

class ECC_Associative:
    #to initialize variable
    def __init__(self, a, b, p):
        self.zero = None
        self.a = a
        self.b = b
        self.p = p
        if ((4 * (a**3)) + (27 * (b**2))) % self.p == 0 or not isPrime(p):
            raise ValueError("The Curve has Defects")

        self.countN, self.containerN = self.recordNcoord()
        if self.countN == p:
            raise ValueError("The Curve is Unsafe")

    #to check the point is on the curve or not
    def check(self, p):
        #if point = point at infinity 
        if p == self.zero:
            return True

        #unpack the point
        x, y = p

        #to check the point is out of range or not & to check the point is on the curve or not
        if not (0 <= x < self.p and 0 <= y < self.p) or \
        not (x**3 + (self.a * x) + self.b - y**2) % self.p == 0:
            raise ValueError("Invalid point")
        return True

    #find the coordinates of given x
    def findcoord(self, x):
        # to check x is out of range or not
        if x < self.p:
            #to transform the ecc equation in order to make find y more clearer and easier
            y = (x**3 + (self.a * x) + self.b) % self.p

            #to brute force the y to check is there any y can match the given x that conform the ecc equation 
            for i in range(0, self.p):
                if i**2 % self.p == y:
                    return((x, i), (x, -i % self.p))
            raise ValueError("Not found")
        else:
            raise ValueError("Out of range")

    #find the total points that can appear on the ecc that generated by the given variable
    def recordNcoord(self):
        #the 1 point means the point at infinity 
        containerN = {self.zero}
        
        #to brute force in order to find the total point 
        for x in range(self.p):
            try:
                p1, p2 = self.findcoord(x)
                #if given x produce 2 same points + 1
                if p1 == p2:
                    containerN.add(p1)
                #if given x produce 2 different points + 2
                else:
                    containerN.add(p1)
                    containerN.add(p2)
            except Exception:
                pass
        return len(containerN), containerN

    def test(self):
        test_container = sorted([p for p in self.containerN if p is not None])
        test_container.append(None)
        n = self.countN
        try:
            for x in range(0, n - 2):
                p1 = test_container[x]
                for y in range(x, n - 1):
                    p2 = test_container[y]
                    for z in range(y, n):
                        p3 = test_container[z]
                        res1 = self.add(self.add(p1, p2), p3)
                        res2 = self.add(p1, self.add(p2, p3))

                        if res1 == res2:
                            pass
                            print(f"({p1} + {p2}) + {p3} = {p1} + ({p2} + {p3}) = {res1}")
                        else:
                            return dedent(f"""\
                            Associative Law Test [Failed]\n
                            Points: [{p1}, {p2}, {p3}]
                            - ({p1} + {p2}) + {p3} = {res1}
                            - {p1} + ({p2} + {p3}) = {res2}""")
            return "Associative Law Test [Success]"
        except Exception as e:
            return f"Failed due to error [{e}]"

    #ecc addition
    def add(self, p1, p2):
        self.check(p1)
        self.check(p2)
        #to check p1 / p2 is infinite point or not
        if p1 == self.zero:
            return p2
        elif p2 == self.zero:
            return p1

        x1, y1 = p1
        x2, y2 = p2

        #coordinates are each other inverse 
        if x1 == x2 and (y1 + y2) % self.p == 0:
            return self.zero
        #coordinates are the same
        elif (x1, y1) == (x2, y2):
            m = ((x1**2 * 3 + self.a) * pow((y1 * 2), -1, self.p)) % self.p
        #coordinates are different
        else:
            m = ((y1 - y2) * pow((x1 - x2), -1, self.p)) % self.p

        #the result of the 2 coordinates adding together 
        x3 = (m**2 - (x1 + x2)) % self.p
        y3 = (m * (x1 - x3) - y1) % self.p

        return (x3, y3)

    #ecc multiplication
    def mul(self, g, n): 
        self.check(g)
        #montgomery ladder
        r0 = self.zero
        r1 = g

        for i in bin(n)[2:]:
            if i == "1":
                r0 = self.add(r0, r1)
                r1 = self.add(r1, r1)
            else:
                r1 = self.add(r1, r0)
                r0 = self.add(r0, r0)
        
        return r0

#test
if __name__ == "__main__":
    k = 5
    a, b, p = -7, 10, 19
    ecc = ECC_Associative(a=a, b=b, p=p) 
    print("-------------------------------------------\n") 
    print(ecc.test())
    print("\n-------------------------------------------") 
